'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Ozone.LanguageDetector.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -- 
        '''procedure
        '''begin
        '''overriding
        '''terminate
        '''delay
        '''limited
        '''synchronized
        '''pragma
        '''tagged.
        '''</summary>
        Friend ReadOnly Property Identifiers_Ada() As String
            Get
                Return ResourceManager.GetString("Identifiers_Ada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mov
        '''syscall
        '''db
        '''# 
        '''.ascii
        '''.text
        '''.global
        '''call
        '''ret
        '''push
        '''lea
        '''pop.
        '''</summary>
        Friend ReadOnly Property Identifiers_Assembly() As String
            Get
                Return ResourceManager.GetString("Identifiers_Assembly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to @echo off
        '''echo
        '''pause
        '''cd
        '''cls
        '''dir
        '''start
        '''ping
        '''move
        '''type
        '''goto
        '''exit.
        '''</summary>
        Friend ReadOnly Property Identifiers_Batch() As String
            Get
                Return ResourceManager.GetString("Identifiers_Batch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to alignas
        '''alignof
        '''#include
        '''iostream
        '''virtual
        '''.h
        '''dynamic_cast
        '''std::
        '''{
        '''}
        '''int main()
        '''//
        ''';
        '''&lt;&lt;
        '''&gt;&gt;.
        '''</summary>
        Friend ReadOnly Property Identifiers_Cpp() As String
            Get
                Return ResourceManager.GetString("Identifiers_Cpp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delegate
        '''{
        '''}
        '''using
        '''namespace
        '''System.Linq;
        '''System.Collections.Generic;
        '''System.Text;
        '''System..
        '''</summary>
        Friend ReadOnly Property Identifiers_CSharp() As String
            Get
                Return ResourceManager.GetString("Identifiers_CSharp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to color:
        '''width:
        '''height:
        '''background-color:
        '''margin:
        '''padding:
        '''position:
        '''text-align:
        '''background:
        '''list-style:
        '''filter:
        '''display:
        '''margin-left:
        '''overflow:
        '''-webkit-perspective:
        '''perspective:
        '''float:
        '''font:
        '''right:
        '''border:
        '''cursor:
        '''{
        '''}.
        '''</summary>
        Friend ReadOnly Property Identifiers_Css() As String
            Get
                Return ResourceManager.GetString("Identifiers_Css", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to elemental
        '''bind
        '''deferred
        '''enumerator
        '''assign
        '''backspace
        '''subroutine
        '''rewrite
        '''write
        '''implicit
        '''format
        '''equivalence
        '''dimension
        '''cp,,pm
        '''namelist
        '''nullify
        '''elsewhere
        '''deallocate
        '''allocatable
        '''allocate
        '''flush
        '''non_overridable
        '''nopass
        '''codimension
        '''contiguous
        '''critical
        '''block
        '''block data
        '''lock
        '''unlock
        '''inquire
        '''intrinsic.
        '''</summary>
        Friend ReadOnly Property Identifiers_Fortran() As String
            Get
                Return ResourceManager.GetString("Identifiers_Fortran", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''&lt;body&gt;
        '''&lt;b&gt;
        '''&lt;i&gt;
        '''&lt;b&gt;
        '''&lt;u&gt;
        '''&lt;p&gt;
        '''&lt;sub&gt;
        '''&lt;sup&gt;
        '''&lt;h1&gt;
        '''&lt;h2&gt;
        '''&lt;h3&gt;
        '''&lt;!DOCTYPE html&gt;
        '''&lt;a href=
        '''&lt;a&gt;
        '''&lt;img src=
        '''&lt;head&gt;
        '''&lt;pre&gt;
        '''&lt;!--
        '''--&gt;.
        '''</summary>
        Friend ReadOnly Property Identifiers_Html() As String
            Get
                Return ResourceManager.GetString("Identifiers_Html", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to assert
        '''{
        '''}
        '''scrictfp
        '''package
        '''super
        '''instanceof
        '''import
        '''javax.
        '''public static void main(String[] args)
        '''java..
        '''</summary>
        Friend ReadOnly Property Identifiers_Java() As String
            Get
                Return ResourceManager.GetString("Identifiers_Java", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to debugger
        '''export
        '''arguments
        '''package
        '''synchronized
        '''transient
        '''Infinity
        '''NaN
        '''prototype
        '''isPrototypeOf
        '''hasOwnProperty
        '''document.write
        '''document.getElementById
        '''.innerHTML
        '''alert.
        '''</summary>
        Friend ReadOnly Property Identifiers_JavaScript() As String
            Get
                Return ResourceManager.GetString("Identifiers_JavaScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #|
        '''defun
        '''equal
        '''equalp
        '''case-insensitive
        '''find-symbol
        '''in-package
        '''hyphens
        '''setf
        '''flet
        '''labels
        '''lambda
        '''funcall
        '''unwind-protect
        '''handler-bind
        '''handler-case
        '''ignore-errors
        '''deftype
        '''.
        '''</summary>
        Friend ReadOnly Property Identifiers_Lisp() As String
            Get
                Return ResourceManager.GetString("Identifiers_Lisp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to repeat
        '''::=
        '''lua_pop
        '''lua_close
        '''lua_
        '''#include
        '''lua.h
        '''va_list
        '''va_start
        '''va_end
        '''extern
        '''luaopen
        '''--[[
        '''--.
        '''</summary>
        Friend ReadOnly Property Identifiers_Lua() As String
            Get
                Return ResourceManager.GetString("Identifiers_Lua", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to threadvar
        '''raise
        '''library
        '''finalization
        '''initialization
        '''procedure
        '''record
        '''repeat
        '''shl
        '''shr
        '''unit
        '''on
        '''inline
        '''label
        '''constructor
        '''continue
        '''destructor
        '''asm
        '''div
        '''downto
        '''implementation
        '''(*
        '''*)
        ''':=
        '''{
        '''}
        '''writeln.
        '''</summary>
        Friend ReadOnly Property Identifiers_Pascal() As String
            Get
                Return ResourceManager.GetString("Identifiers_Pascal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exec
        '''setpgrp
        '''setpriority
        '''shift
        '''__DATA__
        '''__END__
        '''__FILE__
        '''__LINE__
        '''__PACKAGE__
        '''cmp
        '''CORE
        '''exp
        '''eq
        '''ge
        '''gt
        '''le
        '''lock
        '''lt
        '''qw
        '''qx
        '''tr
        '''qq
        '''qr
        '''ne
        '''no
        '''#!/usr/bin/perl
        '''is_dir
        '''use strict;
        '''::.
        '''</summary>
        Friend ReadOnly Property Identifiers_Perl() As String
            Get
                Return ResourceManager.GetString("Identifiers_Perl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to __halt_compiler
        '''clone
        '''callable
        '''empty
        '''die
        '''endswitch
        '''include_once
        '''unset
        '''insteadof
        '''require_once
        '''trait
        '''__CLASS__
        '''__NAMESPACE__
        '''__DIR__
        '''__TRAIT__
        '''__FILE__
        '''__FUNCTION__
        '''__LINE__
        '''__METHOD__
        '''&lt;?php
        '''unlink
        '''header(&apos;
        '''mysql_query.
        '''</summary>
        Friend ReadOnly Property Identifiers_Php() As String
            Get
                Return ResourceManager.GetString("Identifiers_Php", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to def
        '''lambda
        '''exec
        '''except
        '''import
        '''pass
        '''continue
        '''#!/usr/bin/python
        '''.py
        '''Label(
        '''Tkinter.
        '''</summary>
        Friend ReadOnly Property Identifiers_Python() As String
            Get
                Return ResourceManager.GetString("Identifiers_Python", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to puts
        '''def
        '''end
        '''__ENCODING__
        '''__END__
        '''__FILE__
        '''alias
        '''defined?
        '''ensure
        '''module
        '''rescue
        '''unless
        '''undef.
        '''</summary>
        Friend ReadOnly Property Identifiers_Ruby() As String
            Get
                Return ResourceManager.GetString("Identifiers_Ruby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to :=
        '''arrayconst:
        '''bytearray:
        '''number:
        '''string:
        '''charconst:
        '''symconst:
        '''exp:
        '''block:
        '''keyexpr
        '''choose:
        '''cancel:
        '''for:
        '''#(
        '''#[
        '''#! /usr/local/bin/gst
        '''| 
        '''[|.
        '''</summary>
        Friend ReadOnly Property Identifiers_SmallTalk() As String
            Get
                Return ResourceManager.GetString("Identifiers_SmallTalk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''FULL
        '''INSERT
        '''ABORT
        '''ACTION
        '''BEFORE
        '''FROM
        '''ORDER
        '''GO
        '''USE
        '''ALTER
        '''DATABASE
        '''DISTINCT
        '''EXISTS
        '''WHERE
        '''IN
        '''AND
        '''GROUP
        '''TABLE
        '''STATISTICS
        '''SYSTEM_USER
        '''LINENO
        '''CROSS
        '''CREATE.
        '''</summary>
        Friend ReadOnly Property Identifiers_Sql() As String
            Get
                Return ResourceManager.GetString("Identifiers_Sql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to addhandler
        '''addressof
        '''imports
        '''cobj
        '''cint
        '''cchar
        '''cstr
        '''implements
        '''module
        '''sub
        '''^
        '''step
        '''short
        '''resume
        '''raiseevent
        '''removehandler
        '''overloads
        '''byval
        '''byref
        '''optional
        '''shared
        '''object
        '''me..
        '''</summary>
        Friend ReadOnly Property Identifiers_Vb() As String
            Get
                Return ResourceManager.GetString("Identifiers_Vb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;
        '''&gt;
        '''&lt;?xml.
        '''</summary>
        Friend ReadOnly Property Identifiers_Xml() As String
            Get
                Return ResourceManager.GetString("Identifiers_Xml", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
